name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pritunl Profile
        id: pritunl-connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
          start-connection: false
          concealed-outputs: false
          client-version: '1.3.3883.60'
          established-connection-timeout: 120 # Increased timeout for better reliability

      - name: Start VPN Connection Manually
        shell: bash
        run: |
          set -x  # Enable verbose logging
          pritunl-client start ${{ steps.pritunl-connection.outputs.client-id }} \
            --password "${{ secrets.PRITUNL_PROFILE_PIN || '' }}"
          sleep 20 

      - name: Display Full VPN Connection Status
        shell: bash
        run: |
          set -x  # Enable verbose logging
          pritunl-client list --json | jq .

      # 3) SSH & deploy
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          timeout: 300s
          command_timeout: 600s
          script: |
              cd /home/ubuntu/infina-pfa
              git checkout develop
              git pull origin main
              npm install
              npm run build
              pm2 restart infina-pfa 
              echo "Deployment completed!!"

      # Stop VPN connection using stored client ID (always run, even on failure)
      - name: Stop VPN Connection Manually
        if: ${{ always() }}
        shell: bash
        run: |
          set -x  # Enable verbose logging
          pritunl-client stop ${{ steps.pritunl-connection.outputs.client-id }}
